###Q.3(a) Write python from scratch for 2D Circular convolution using  Doubly Block Circulant matrices method between input=np.array([[1,2,3],[4,5,6],[7,8,9]])and filter=np.array([[1,2,1],[0,0,0],[-1,-2,-1]])

In [4]:
import numpy as np

input1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Input Shape: ', input1.shape)
print('Input Matrix:\n',input1)

f = np.array([[1, 2, 1], [0, 0, 0], [-1, -2, -1]])
print('Filter1 Shape: ', f.shape)
print('Filter Matrix:\n',f)

for j in range(3):
    locals()["H"+str(j)]=f[j,:]
    for i in range(2):
        temp=np.roll(f[j,:],i+1)
        locals()["H"+str(j)]=np.c_[locals()["H"+str(j)],temp]

    #Toeplitz matrix
mat=H0
for j in range(1,3,1):
    mat=np.r_[mat,locals()["H"+str(j)]]

H_matrix=mat
for i in range(1,3,1):
    temp=np.roll(mat,i*3,axis=0)
    H_matrix=np.c_[H_matrix,temp]
print('Final Toeplitz matrix:\n',H_matrix)

    #input vector
f=input1[0,:]
for j in range(1,3,1):
    temp=input1[j,:]
    f=np.r_[f,temp]  

    #output    
output=np.matmul(H_matrix,f)
output=output.reshape((3,3))
print('Output:\n',output)





   

Input Shape:  (3, 3)
Input Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Filter1 Shape:  (3, 3)
Filter Matrix:
 [[ 1  2  1]
 [ 0  0  0]
 [-1 -2 -1]]
Final Toeplitz matrix:
 [[ 1  1  2 -1 -1 -2  0  0  0]
 [ 2  1  1 -2 -1 -1  0  0  0]
 [ 1  2  1 -1 -2 -1  0  0  0]
 [ 0  0  0  1  1  2 -1 -1 -2]
 [ 0  0  0  2  1  1 -2 -1 -1]
 [ 0  0  0  1  2  1 -1 -2 -1]
 [-1 -1 -2  0  0  0  1  1  2]
 [-2 -1 -1  0  0  0  2  1  1]
 [-1 -2 -1  0  0  0  1  2  1]]
Output:
 [[-12 -12 -12]
 [-12 -12 -12]
 [ 24  24  24]]
