###(a) Write python from scratch for computing 2D DFT{X(k,l)} of the following 2D array

 (i) x(m,n) = np.array([[1, 0],[2, 1]])
 
 (ii) x(m,n) = np.array([[1,2, 3,4], [5, 6, 7, 8], [9,10,11,12], [13,14,15,16]])

In [12]:
def DFT(input_mat):
    m, n = input_mat.shape
    dft = np.zeros((m, n),dtype=complex)
    for u in range(m):
        for v in range(n):
            mat_sum = 0
            for k in range(m):
                for l in range(n):
                    w = cmath.exp(- 2j * np.pi * ((u * k) / m + (v * l) / n))
                    mat_sum +=  w * input_mat[k,l]
            
            dft[u,v] = mat_sum
                
    return dft

import numpy as np
import cmath

#Q.2 a
input1 = np.array([[1, 0],[2, 1]])  
print('input1:\n',input1)
output1 = DFT(input1)
print('output1:\n',output1)

#Q.2 b
input2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print('input2:\n',input2)
output2 = DFT(input2)
print('output2:\n',output2)

input1:
 [[1 0]
 [2 1]]
output1:
 [[ 4.+0.0000000e+00j  2.-1.2246468e-16j]
 [-2.-3.6739404e-16j  0.+0.0000000e+00j]]
input2:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
output2:
 [[ 1.36000000e+02+0.00000000e+00j -8.00000000e+00+8.00000000e+00j
  -8.00000000e+00-9.79717439e-15j -8.00000000e+00-8.00000000e+00j]
 [-3.20000000e+01+3.20000000e+01j  3.55271368e-15+1.22712272e-15j
   2.50990696e-15+0.00000000e+00j -2.13162821e-14+6.42753875e-15j]
 [-3.20000000e+01-1.42059029e-14j  3.48838644e-15+0.00000000e+00j
   0.00000000e+00+2.44929360e-15j -6.79864668e-14+3.55271368e-15j]
 [-3.20000000e+01-3.20000000e+01j -2.48689958e-14+2.87482507e-15j
  -8.31807528e-14+3.55271368e-15j -5.68434189e-14+1.90501133e-15j]]
